/// General purpose utility functions for all classes to use

#pragma once

using namespace std;

extern bool com_op;                            // Set to true for command line output

#include "struct.hh"
#include "equation.hh"

void emsg(const string &msg);
void alert_input(const string &msg);
void run_error(const string &msg);
void run_end(const string &msg);
void emsg_input(const string &msg);
void end_code();
void display_error(string msg, bool internal);
void display_warning(string msg);
void display_terminate(string msg);
string trim(string te);
string remove_prime(string te);
string remove_quote(string te);
vector <string> split(const string &s, char delimiter, bool notrim = false);
vector <string> split_with_bracket(const string &s, char delimiter);
vector <string> split_with_curly_bracket(const string &s, char delimiter);
vector <string> split_basic(const string &s, char delimiter);

string toLower(string st);
string toUpper(string st);
unsigned int find_in(const vector <unsigned int> &vec, const unsigned int val);
unsigned int find_in(const vector <double> &vec, const double val);
unsigned int find_in(const vector <string> &vec, const string val);
unsigned int find_in(const vector <string> &vec, const string val, unsigned int guess);
unsigned int find_in(string st1, string st2);
unsigned int find_in(const vector <bool> &vec, const bool val);
unsigned int find_in(const vector <Warn> &vec, const unsigned int val);
unsigned int find_in(const vector <IEGref> &vec, const IEGref val);
unsigned int integer(string st);
double number(string st);
vector <double> get_number_vec(string st);
double ran();
double uniform_sample(double min, double max, string &warn);
double uniform_from_cdf(double p, double min, double max, string &warn);
double uniform_probability(double min, double max);
double power_sample(double min, double max, double power, string &warn);
double power_from_cdf(double p, double min, double max, double power, string &warn);
double power_probability(double x, double min, double max, double power);
double inverse_sample(double min, double max, string &warn);
double inverse_from_cdf(double p, double min, double max, string &warn);
double inverse_probability(double x, double min, double max);
double normal_sample(double mean, double sd, string &warn);
double normal_from_cdf(double p, double mean, double sd, string &warn);
int normal_int_sample(double si, string &warn);
double normal_probability(double x, double mean, double sd);
double lognormal_sample(double mean, double cv, string &warn);
double lognormal_from_cdf(double p, double mean, double cv, string &warn);
double lognormal_probability(double x, double mean, double cv); 
double lognormal_upper_probability(double xmin, double mean, double cv);
double lognormal_upper_probability_no_log(double xmin, double mean, double cv);
double weibull_sample(double scale, double shape, string &warn);
double weibull_probability(double x, double scale, double shape);
double weibull_upper_probability(double xmin, double scale, double shape);
double weibull_upper_probability_no_log(double xmin, double scale, double shape);
double gamma_sample(double mean, double cv, string &warn);
double gamma_from_cdf(double p, double mean, double cv, string &warn);
double gamma_probability(double x, double mean, double cv);
double gamma_upper_probability(double xmin, double mean, double cv);
double gamma_upper_probability_no_log(double xmin, double mean, double cv);
double beta_sample(double alpha, double beta, string &warn);
double beta_from_cdf(double p, double alpha, double beta, string &warn);
double beta_probability(double x, double alpha, double beta, string &warn);
unsigned int poisson_sample(double lam, string &warn);
double poisson_probability(int i, double lam);
double poisson_upper_probability_no_log(int imin, double lam);
unsigned int neg_binommial_sample(double mean, double p, string &warn);
double neg_binomial_probability(int i, double mean, double p);
unsigned int bernoulli_sample(double z, string &warn);
unsigned int bernoulli_from_cdf(double p, double z, string &warn);
double bernoulli_probability(unsigned int x, double p);
double exp_rate_sample(double rate, string &warn);
double exp_rate_probability(double x, double rate); 
double exp_rate_upper_probability(double xmin, double rate);
double exp_rate_upper_probability_no_log(double xmin, double rate);
double exp_mean_sample(double mean, string &warn);
double exp_mean_probability(double x, double mean);
double exp_mean_from_cdf(double p, double mean, string &warn);
double exp_mean_upper_probability(double xmin, double mean);
double exp_mean_upper_probability_no_log(double xmin, double mean);
double gamma_alpha_sample(double alpha, string &warn);
double gamma_alpha_from_cdf(double p, double alpha, string &warn);
double gamma_alpha_probability(double x, double alpha);
unsigned int binomial_sample(double p, unsigned int n, string &warn);
double binomial_probability(unsigned int num, double p, unsigned int n);
double period_sample(double time, string &warn);
double period_probability(double x, double time);
double period_upper_probability(double x, double time);
double rectify(double val);
bool equal_vec(const vector <string> &vec1, const vector <string> &vec2);
bool equal_vec(const vector <unsigned int> &vec1, const vector <unsigned int> &vec2);
bool equal_vec(const vector <bool> &vec1, const vector <bool> &vec2);
bool equal_vec(const vector <double> &vec1, const vector <double> &vec2);

vector <unsigned int> get_list(unsigned int num);
string stringify(const vector <string> &arr);
string stringify(const vector <EquationInfo> &value, const vector <Dependency> &dep);
bool includes(string st, string ch);
DepInfo get_dep_info(const string &te, unsigned int i, const string &not_allowed);
bool str_eq(const string &te, unsigned int i, const string &te2);
SwapResult swap_index(string &te, const vector <DepConv> &dep_conv);
bool in_text(const string &te, unsigned int i, string te2);
SwapResult swap_template(string te, const vector <DepConv> &dep_conv);
string swap_index_temp(const vector <DepConv> &dep_conv, const SwapResult &temp, string &warn);
ParamProp get_param_prop(string st);
unsigned int add_to_vec(vector <unsigned int> &vec, unsigned int val);
unsigned int add_to_vec(vector <string> &vec, string val);
unsigned int add_to_vec(vector <unsigned int> &vec, unsigned int val, HashSimp &hash);
unsigned int add_to_vec(vector <ParamRef> &vec, unsigned int th, unsigned int index, Hash &hash);
unsigned int add_to_vec(vector <IEGref> &vec, const IEGref &val, Hash &hash); 
double geo_dist(double lat1, double lng1, double lat2, double lng2);
void print(string name, const vector <double> &vec);
unsigned int get_core();
MemUsage get_mem_usage();
void print_diag(string te);
void print(string name, const vector <unsigned int> &vec);
void printsm(string name, const vector <double> &vec);
void print(string name, const vector < vector <double> > &vec);
void print(string name, const vector < vector <unsigned int> > &mat);
void print(string name, const Table &tab);

bool dif(double a, double b, double thresh);
bool dif(const vector <double> &a, const vector <double> &b, double thresh);
unsigned int which_dif(const vector <double> &a, const vector <double> &b, double thresh);
bool dif(const vector < vector <double> > &a, const vector < vector <double> > &b, double thresh);
vector <unsigned int> which_dif(const vector < vector <double> > &a, const vector < vector <double> > &b, double thresh);
bool difi(unsigned int a, unsigned int b);
bool difi(const vector <unsigned int> &a, const vector <unsigned int> &b);
bool difi(const vector < vector <unsigned int> > &a, const vector < vector <unsigned int> > &b);
string replace(string st, string st1, string st2);
void remove_tab(string &st);
void remove_cr(string &st);
bool is_percent(string val);
string get_param_name_with_dep(const Param &par, const vector <Dependency> &dep, unsigned int index);
void param_vec_add_affect(vector <AffectLike> &vec, const AffectLike &al);
double sum(const vector <double> &vec);
double sum(const vector < vector <double> > &mat);
unsigned int sum(const vector <unsigned int> &vec);
double sum_mult(const vector < vector <double> > &M1, const vector < vector <unsigned int> > &M2);
double mean(const vector <double> &val);
double min(const vector <double> &val);
double max(const vector <double> &val);
unsigned int max(const vector <unsigned int> &val);
unsigned int min(const vector <unsigned int> &val);
int round_int(double val);
int floor_int(double val);
vector <int> round_int(const vector <double> &val);
string cpu_percent(long time, long total_time);
string tstr(double value, unsigned int dig=UNSET);
unsigned int core();
unsigned int num_core();
bool op();
vector <unsigned int> seq_vec(unsigned int N);
vector <unsigned int> seq_vec(unsigned int n1, unsigned int n2);
vector <bool> true_vec(unsigned int N);
string get_affect_name(AffectType type);
Prior convert_text_to_prior(string te, unsigned int line_num, string in, bool dist);
string get_prior_string(Prior prior);
void init_log_sum();
double factorial(unsigned int n);
double choose(unsigned int N, unsigned int r);
double log_int(unsigned int n);
vector <double> dirichlet_sample(const vector <double> &alpha);
double dirichlet_probability(const vector <double> &frac, const vector <double> &alpha);
vector <unsigned int>  multinomial_sample(unsigned int N_total, const vector <double> &frac);
double multinomial_probability(unsigned int N_total, const vector <unsigned int> &x, const vector <double> &frac);
double multinomial_samp_probability(const vector <unsigned int> &x, const vector <double> &frac);
unsigned int get_event_before(unsigned int e, const vector <Event> &ev);
unsigned int get_event_after(unsigned int e, const vector <Event> &ev);
double get_log_zero_one(double val);
void set_seed(const int core, const Details &details, unsigned int seed_tag);
void check_bp(double &bp);
double nm_trans_like(TransType type, double dtdiv, double dt, const vector <double> &ref_val);
vector <string> comma_split(string te);
unsigned int get_op_step(unsigned int nnumber);
vector <unsigned int> true_list(const vector <bool> &vec);	
vector <unsigned int> false_list(const vector <bool> &vec);
vector <unsigned int> combine(const vector <unsigned int> &vec1, const vector <unsigned int> &vec2);	
bool begin_str(string st, string st2);
bool end_str(string st, string st2);
bool check_thresh(DistText dist, DistQuant dq, double val, string &err);
string trunc(string te, unsigned int len);
string add_escape_char(string te);
string replace_arrow(string te);
void percentage(double val, double val2, bool sup=false);
string pad(string te, unsigned int len);
void percentage_start(PercentType type, bool sup=false, unsigned int gen=UNSET);
void percentage_end(bool sup=false);	
string find_root(string file);
void wait();
void add_full_stop(string &te);
double memory_usage();
double total_memory();
double memory_available();
string mem_print(double mem);
double clip(double val, double thresh);
double exp_clip(double val);
unsigned int get_ti(double t);
unsigned int get_ti_lower(double t);
unsigned int get_ti_next(double t_next, const Details &details);
unsigned int get_ti_over(double tdiv);
bool on_timestep(double t, const Details &details);
double calc_tdiv(double t, const Details &details);
double calc_t(double tdiv, const Details &details);
void add_alg_warning(string te, unsigned int sample, vector <AlgWarn> &alg_warn);
void eqn_type_error(EqItemType type, unsigned int ref);
double calculate_operation(EqItemType op, vector <double> &num, CalcError &calc_err);
void calc_error(CalcError err, string eq_text);
void solve_cubic_spline_test();
CubicSpline solve_cubic_spline(const vector <double> &x, vector <double> f, SplineType type);
double calculate_cubic_spline(double xf, const CubicSpline &cspl);
void calculate_cubic_spline_precalc(vector <double> &precalc, unsigned int i, const vector <unsigned int> &list_time, const vector <CubicDiv> &div, const CubicSpline &cspl);
string prop_type_str(PropType type);
void term_out(string te);
string sig_fig(double num, unsigned int fig);
string precision(double num, unsigned int dig);
string get_cpu_time(double tics);
double median(vector <double> vec);
bool param_omega(string name);
bool contains_space(string te);
string output_table(const Table &tab);
Stat get_statistic(vector <double> &vec);
vector <unsigned int> remove_repeated(const vector <unsigned int> &list);
vector <unsigned int> combine_lists(const vector < vector <unsigned int> > &lists);
void print_random(string te);

// In utils_eqn.cc
EquationInfo add_equation_info(string _te, EqnType _type, unsigned int _p = UNSET, unsigned int _cl = UNSET);
string check_valid_name(string name, string type);
unsigned int der_func_check(unsigned int i, string te, string name, string &warn_der);
string basic_equation_check(string &te, EqnType eqn_type);
string check_brackets_match(string te);
string check_chnotallowed(string te);
CommandLine get_command_tags(string trr, unsigned int line_num);
CommandLine syntax_error(string emsg);
void get_default_name(string &name, Command cname);

unsigned int param_end(const string &st, unsigned int i, string &emsg);
Poss sample_possibility(const vector <Poss> &pos);
double sample_probability(unsigned int i, const vector <Poss> &pos);
string trunc(const string &str);
double indfac(const Individual &ind);
double prior_probability(double x, const Prior &pri, const vector <double> &precalc,const vector <Equation> &eqn);
void add_on_like(const Like li1, Like &li2);
double calc_al(const Like &like_ch, double dprob, const BurnInfo &burn_info);
void print_like(const Like &like);
void print(string te);
void print(double num, string te);

/// In utils_check
void test_jeffreys();
void test_distribution();
void generate_data();
void simulate_trans_exp();
void test_incomplete_distribution();
void mvn_prior_check();
void mvn_jeffreys_check();
double mem(const vector < vector < vector <unsigned int> > > &ten);
double mem(const vector < vector <unsigned int> > &ten);
double mem(const vector <double> &ten);
double mem(const vector < vector <double> > &ten);
double mem(const vector <unsigned int> &ten);
double mem(const vector <unsigned long long> &ten);
double mem(const SwapResult &sr);
double mem(const Table &tab);
double mem(const PropInfo &pi);
double mem(const vector <Calculation> &calc);
double mem(const vector < vector <int> > &ten);
double mem(const vector <Sample> &vec);
double mem(const HashSimp &hash);
double mem(const Particle &pa);
double mem(const SpecPrecalc &spp);
double mem(const vector < vector <bool> > &mat);
double mem(const vector <bool> &vec);
double mem(const ObsModel &val);
double mem(const Spline &spl);
double mem(const vector <string> &vec);
double mem(const Dependency &de);
double mem(const Prior &vec);
double mem(const string st);
double mem(const EquationInfo &ei);
double mem(const vector <EquationInfo> &vec);
double mem(const vector <AffectLike> &vec);
void check_cdf_function();
void check_nm_trans_incomp_like_no_log();